# Deployment values for argocd-apps
# Only add here the components that should be deployed into every cluster environment
argocd:
  namespace: argocd
  project: default
  appNameSuffix: ''
source:
  repoURL: https://github.com/DNXLabs/cluster-prod-apps-metadata.git
  targetRevision: master
destination:
  cluster: https://kubernetes.default.svc
syncPolicy: {prune: true, selfHeal: true} # auto-sync enabled

apps:
  poc-application-blueprint:
    project: default
    namespace: prod
    path: charts/poc-application-blueprint
    helm_parameters:
      service.type: NodePort
      service.port: "80"
      # image.tag: v0.0.1
      ingress.enabled: "true"
      ingress.annotations.kubernetes\.io\/ingress\.class: alb
      ingress.annotations.alb\.ingress\.kubernetes\.io\/group\.name: prod-apps
      ingress.annotations.alb\.ingress\.kubernetes\.io\/scheme: internet-facing
      ingress.annotations.alb\.ingress\.kubernetes\.io\/certificate-arn: "arn:aws:acm:ap-southeast-2:960722883904:certificate/50e2b8cb-b10c-42ee-9a30-a282c4efba63"
      ingress.annotations.alb\.ingress\.kubernetes\.io\/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
      ingress.annotations.alb\.ingress\.kubernetes\.io\/ssl-redirect: '443'
      ingress.annotations.alb\.ingress\.kubernetes\.io\/target-type: instance
      ingress.annotations.alb\.ingress\.kubernetes\.io\/success-codes: "200"
      ingress.annotations.alb\.ingress\.kubernetes\.io\/healthcheck-path: /
      ingress.annotations.alb\.ingress\.kubernetes\.io\/group\.order: "100"
      ingress.hosts[0].host: blueprint.citadel-prod.bubbletea.dnx.one
      ingress.hosts[0].paths[0]: "/"
      revisionHistoryLimit: "2"